# Generated by Django 5.0.7 on 2024-07-24 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.TextField()),
                ('kod', models.TextField(null=True)),
                ('zobrazit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hodnota', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('obrazek', models.TextField()),
                ('nazev', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('cena', models.TextField(null=True)),
                ('mena', models.TextField(null=True)),
                ('published_on', models.DateTimeField(null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.attributename')),
                ('hodnota_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.TextField(null=True)),
                ('attributes_ids', models.ManyToManyField(to='quickstart.attribute')),
                ('obrazek_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quickstart.image')),
                ('products_ids', models.ManyToManyField(to='quickstart.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(through='quickstart.ProductAttributes', to='quickstart.attribute'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nazev', models.TextField(null=True)),
                ('obrazek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(through='quickstart.ProductImage', to='quickstart.image'),
        ),
    ]
